[LOCAL]
enable.hive = false
hive.database = null
kafka.topic = sbdl_kafka_cloud
kafka.api.key = JQIYFTKOUO5W6S4X
kafka.api.secret = 9kWCVtO7pirJWAIhAnX/d3XNCZhpngX+kJ4mN2eGY55B4QfhQbeh20wsYwdn5IOs
# Required connection configs for Kafka producer, consumer, and admin
kafka.bootstrap.servers=pkc-312o0.ap-southeast-1.aws.confluent.cloud:9092
kafka.security.protocol=SASL_SSL
kafka.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username='{}' password='{}';
kafka.sasl.mechanism=PLAIN
# Required for correctness in Apache Kafka clients prior to 2.6
kafka.client.dns.lookup=use_all_dns_ips

# Best practice for higher availability in Apache Kafka clients prior to 3.0
session.timeout.ms=45000

# Best practice for Kafka producer to prevent data loss
acks=all

client.id=ccloud-java-client-93e60064-7653-41e3-a153-0533d394d243

[QA]
enable.hive = true
hive.database = sbdl_db_qa
kafka.topic = sbdl_kafka_qa
[PROD]
enable.hive = true
hive.database = sbdl_db
kafka.topic = sbdl_kafka

